pallets := "Omnipool Stableswap AssetRegistry EVM DynamicFees EmaOracle MultiTransactionPayment Tokens Balances EVMAccounts Ethereum Aura System EVMChainId Timestamp XYK"
#pallets := "Stableswap"

scaper-bin := "./../../hydration-node/target/debug/scraper"

make-snapshot binary_path blockhash:
    @echo "Creating snapshot with binary: {{binary_path}}"
    @echo "Block hash: {{blockhash}}"
    {{binary_path}} save-storage --pallet {{pallets}} --at {{blockhash}} --uri wss://rpc.hydradx.cloud:443 --path ./
    mv ./SNAPSHOT data/MAINNET

prepare:
    @echo "Preparing"
    ./target/debug/prepare-snapshot

